use_frameworks!

target 'QDHeaderTabbarViewController_Example' do
  pod 'QDHeaderTabbarViewController', :path => '../'

  target 'QDHeaderTabbarViewController_Tests' do
    inherit! :search_paths

    
  end
end
